### PR TITLE
fix compatibility with fasthttprouter v0.1

### PR DESCRIPTION
**Pull request by buaazp**
I relased `fasthttprouter` v0.1 and remove the `Params` struct now.

This PR is fix compatibility with these changes.

### CODE REVIEW

**Comment by buaazp** [comment]
CI fails because the glide version not matched.

**Comment by appleboy** [comment]
cc @gosilent

**Comment by appleboy** [comment]
I will take this.

**Comment by appleboy** [comment]
@buaazp I already merged this commit. Please see the commit. https://github.com/go-gas/gas/commit/7251800b32e6842170974046464cee114599d926

Thanks for your contribution.

**Comment by buaazp** [comment]
👍

**Pull request closed without merging**
